from typing import Any, Awaitable, Callable, Iterable, List, Optional, Tuple, Union

class color_matrix:
    @staticmethod
    def clear(port: int) -> None: ...
    @staticmethod
    def get_pixel(port: int, x: int, y: int) -> Tuple[int, int]: ...
    @staticmethod
    def set_pixel(port: int, x: int, y: int, pixel: Tuple[int, int]) -> None: ...
    @staticmethod
    def show(port: int, pixels: List[Tuple[int, int]]) -> None: ...
