from typing import Any, Awaitable, Callable, Iterable, List, Optional, Tuple, Union

class device:
    @staticmethod
    def data(port: int) -> Tuple[int, ...]: ...
    @staticmethod
    def id(port: int) -> int: ...
    @staticmethod
    def get_duty_cycle(port: int) -> int: ...
    @staticmethod
    def ready(port: int) -> bool: ...
    @staticmethod
    def set_duty_cycle(port: int, duty_cycle: int) -> None: ...
