from typing import Any, Awaitable, Callable, Iterable, List, Optional, Tuple, Union

class distance_sensor:
    @staticmethod
    def clear(port: int) -> None: ...
    @staticmethod
    def distance(port: int) -> int: ...
    @staticmethod
    def get_pixel(port: int, x: int, y: int) -> int: ...
    @staticmethod
    def set_pixel(port: int, x: int, y: int, intensity: int) -> None: ...
    @staticmethod
    def show(port: int, pixels: List[int]) -> None: ...
