from typing import Any, Awaitable, Callable, Iterable, List, Optional, Tuple, Union
class motor_pair:
    PAIR_1: int = 0
    PAIR_2: int = 1
    PAIR_3: int = 2
    @staticmethod
    def move(pair: int, steering: int, *, velocity: int = 360, acceleration: int = 1000) -> None: ...
    @staticmethod
    def move_for_degrees(pair: int, degrees: int, steering: int, *, velocity: int = 360, stop: int = 1, acceleration: int = 1000, deceleration: int = 1000) -> Awaitable[int]: ...
    @staticmethod
    def move_for_time(pair: int, duration: int, steering: int, *, velocity: int = 360, stop: int = 1, acceleration: int = 1000, deceleration: int = 1000) -> Awaitable[int]: ...
    @staticmethod
    def move_tank(pair: int, left_velocity: int, right_velocity: int, *, acceleration: int = 1000) -> None: ...
    @staticmethod
    def move_tank_for_degrees(pair: int, degrees: int, left_velocity: int, right_velocity: int, *, stop: int = 1, acceleration: int = 1000, deceleration: int = 1000) -> Awaitable[int]: ...
    @staticmethod
    def move_tank_for_time(pair: int, left_velocity: int, right_velocity: int, duration: int, *, stop: int = 1, acceleration: int = 1000, deceleration: int = 1000) -> Awaitable[int]: ...
    @staticmethod
    def pair(pair_slot: int, left_motor_port: int, right_motor_port: int) -> None: ...
    @staticmethod
    def stop(pair: int, *, stop: int = 1) -> None: ...
    @staticmethod
    def unpair(pair: int) -> None: ...
